import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {manualBundle} from '../scripts/build-manual-supabase-sql.mjs';
const file=async name=>(await readFile(new URL(`../supabase/manual/${name}`,import.meta.url),'utf8')).replaceAll('\r\n','\n');
const roles='CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;';
const legacy=`CREATE TABLE public.hospitality_inquiries(
  id bigint generated by default as identity primary key,
  hotel_name text not null,website_url text not null,contact_name text not null,email text not null,
  notes text,status text not null default 'new',created_at timestamptz not null default now());
  INSERT INTO public.hospitality_inquiries(hotel_name,website_url,contact_name,email) VALUES('Synthetic legacy','https://example.com','QA','qa@example.com');`;
const verify=async db=>{
  const result=await db.query(await file('02-verify.sql'));
  assert.ok(result.rows.length>20);
  assert.ok(result.rows.every(row=>row.result==='PASS'),JSON.stringify(result.rows.filter(row=>row.result!=='PASS')));
};
test('manual SQL is generated from canonical migrations and passes on an empty project',async()=>{
  assert.equal(await file('01-apply.sql'),await manualBundle());
  const db=new PGlite();
  try{
    await db.exec(roles);
    assert.ok((await db.query(await file('00-inspect.sql'))).rows[0].schema_inventory);
    await db.exec(await manualBundle());await verify(db);
    assert.equal((await db.query('SELECT count(*)::int as total FROM public.hospitality_inquiries')).rows[0].total,0);
    assert.equal((await db.query('SELECT count(*)::int as total FROM public.wuus_inquiry_notifications')).rows[0].total,0);
  }finally{await db.close();}
});
test('manual apply preserves legacy rows, revokes column grants and old outbox policies on rerun',async()=>{
  const db=new PGlite();
  try{
    await db.exec(roles+legacy+`ALTER TABLE public.hospitality_inquiries ENABLE ROW LEVEL SECURITY;
      CREATE POLICY old_open ON public.hospitality_inquiries FOR ALL TO public USING(true) WITH CHECK(true);
      GRANT ALL ON public.hospitality_inquiries TO anon,authenticated;
      GRANT SELECT(email),INSERT(email),UPDATE(email) ON public.hospitality_inquiries TO public,anon,authenticated;
      CREATE TABLE public.business_scores(id bigint generated by default as identity primary key,score int);
      INSERT INTO public.business_scores(score) VALUES(42);
      GRANT SELECT(score) ON public.business_scores TO public;`);
    await db.exec(await manualBundle());await verify(db);
    assert.equal((await db.query('SELECT count(*)::int as total FROM public.hospitality_inquiries')).rows[0].total,1);
    assert.equal((await db.query('SELECT score FROM public.business_scores')).rows[0].score,42);
    assert.equal((await db.query('SELECT count(*)::int as total FROM public.wuus_inquiry_notifications')).rows[0].total,0,'No historical mass emails');
    await db.exec(`CREATE POLICY old_outbox_open ON public.wuus_inquiry_notifications FOR ALL TO public USING(true) WITH CHECK(true);
      GRANT SELECT(request_id) ON public.wuus_inquiry_notifications TO public;`);
    await db.exec(await manualBundle());await verify(db);
    const payload=JSON.stringify({hotel_name:'QA',website_url:'https://example.com',contact_name:'QA',email:'qa@example.com',notes:'',source:'review',request_type:'review',consent_version:'2026-10-07'});
    await db.exec('SET ROLE service_role');
    assert.equal((await db.query('SELECT public.submit_wuus_inquiry(gen_random_uuid(),repeat(\'f\',64),$1::jsonb) as result',[payload])).rows[0].result,'saved');
    assert.equal((await db.query('SELECT count(*)::int as total FROM public.wuus_inquiry_notifications')).rows[0].total,1);
    await db.exec('RESET ROLE');
  }finally{await db.close();}
});
test('manual apply rejects an incompatible legacy id and rolls schema changes back',async()=>{
  const db=new PGlite();
  try{
    await db.exec(roles+legacy.replace('bigint generated by default as identity','uuid default gen_random_uuid()'));
    await assert.rejects(db.exec(await manualBundle()),/unsupported type uuid/);
    await db.exec('ROLLBACK');
    assert.equal((await db.query("SELECT to_regclass('public.wuus_inquiry_notifications') as table_name")).rows[0].table_name,null);
    assert.equal((await db.query('SELECT count(*)::int as total FROM public.hospitality_inquiries')).rows[0].total,1);
  }finally{await db.close();}
});
test('manual apply stops on a transitive public view or callable definer instead of claiming data is private',async()=>{
  const db=new PGlite();
  try{
    await db.exec(roles+legacy+`CREATE VIEW public.first_view AS SELECT email FROM public.hospitality_inquiries;
      CREATE VIEW public.second_view AS SELECT email FROM public.first_view;
      GRANT SELECT(email) ON public.second_view TO anon;`);
    await assert.rejects(db.exec(await manualBundle()),/publicly readable dependent views/);await db.exec('ROLLBACK');
    await db.exec(`DROP VIEW public.second_view; DROP VIEW public.first_view;
      CREATE FUNCTION public.old_lead_reader() RETURNS bigint LANGUAGE sql SECURITY DEFINER AS 'SELECT count(*) FROM public.hospitality_inquiries';`);
    await assert.rejects(db.exec(await manualBundle()),/public security-definer routines/);await db.exec('ROLLBACK');
    assert.equal((await db.query('SELECT count(*)::int as total FROM public.hospitality_inquiries')).rows[0].total,1);
  }finally{await db.close();}
});
