-- Review in staging first. Back up existing table and policies before applying.
begin;

create table if not exists public.hospitality_inquiries (
  id bigint generated by default as identity primary key,
  hotel_name text not null, website_url text not null, contact_name text not null,
  email text not null, notes text, status text default 'new' not null,
  created_at timestamptz default now() not null
);
alter table public.hospitality_inquiries
  add column if not exists request_id uuid,
  add column if not exists request_payload jsonb,
  add column if not exists source text,
  add column if not exists request_type text,
  add column if not exists consent_at timestamptz,
  add column if not exists consent_version text;
create unique index if not exists hospitality_inquiries_request_id on public.hospitality_inquiries(request_id);
alter table public.hospitality_inquiries enable row level security;
revoke all on table public.hospitality_inquiries from public, anon, authenticated;
grant select, insert, update, delete on public.hospitality_inquiries to service_role;
-- Existing public policies are deliberately removed; restore only from reviewed backup.
do $$ declare entry record; column_names text;
begin
  -- Table REVOKE alone does not revoke pre-existing column-level grants.
  select string_agg(format('%I',attname),',') into column_names from pg_attribute
    where attrelid='public.hospitality_inquiries'::regclass and attnum>0 and not attisdropped;
  execute format('revoke all (%s) on table public.hospitality_inquiries from public, anon, authenticated',column_names);
  for entry in select policyname from pg_policies where schemaname = 'public' and tablename = 'hospitality_inquiries'
  loop execute format('drop policy %I on public.hospitality_inquiries', entry.policyname); end loop;
  -- Identity sequence may already exist under a different name.
  if pg_get_serial_sequence('public.hospitality_inquiries', 'id') is not null then
    execute format('revoke all on sequence %s from public, anon, authenticated', pg_get_serial_sequence('public.hospitality_inquiries', 'id'));
    execute format('grant usage, select on sequence %s to service_role', pg_get_serial_sequence('public.hospitality_inquiries', 'id'));
  end if;
end $$;

create schema if not exists wuus_private;
revoke all on schema wuus_private from public, anon, authenticated;
create table if not exists wuus_private.inquiry_rate_limits (
  network_key text primary key,
  window_start timestamptz not null,
  requests integer not null check (requests > 0)
);
revoke all on wuus_private.inquiry_rate_limits from public, anon, authenticated;

create or replace function public.submit_wuus_inquiry(p_request_id uuid, p_network_key text, p_payload jsonb)
returns text language plpgsql security definer set search_path = '' as $$
declare existing_payload jsonb; bucket wuus_private.inquiry_rate_limits%rowtype;
begin
  if p_request_id is null or p_network_key !~ '^[a-f0-9]{64}$' or p_network_key is null
    or p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'Invalid request';
  end if;
  -- Request lock prevents concurrent retries on different networks from inserting twice.
  perform pg_advisory_xact_lock(hashtextextended(p_request_id::text, 0));
  select request_payload into existing_payload from public.hospitality_inquiries where request_id = p_request_id;
  if found then
    if existing_payload = p_payload then return 'duplicate'; else return 'conflict'; end if;
  end if;
  -- Network lock and durable counter work across serverless instances.
  perform pg_advisory_xact_lock(hashtextextended(p_network_key, 1));
  select * into bucket from wuus_private.inquiry_rate_limits where network_key = p_network_key;
  if not found or bucket.window_start <= now() - interval '15 minutes' then
    insert into wuus_private.inquiry_rate_limits values (p_network_key, now(), 1)
      on conflict (network_key) do update set window_start = excluded.window_start, requests = 1;
  elsif bucket.requests >= 5 then return 'limited';
  else update wuus_private.inquiry_rate_limits set requests = requests + 1 where network_key = p_network_key;
  end if;
  insert into public.hospitality_inquiries
    (request_id, request_payload, hotel_name, website_url, contact_name, email, notes, status, source, request_type, consent_at, consent_version)
  values (p_request_id, p_payload, p_payload->>'hotel_name', p_payload->>'website_url', p_payload->>'contact_name',
    p_payload->>'email', p_payload->>'notes', 'new', p_payload->>'source', p_payload->>'request_type', now(), p_payload->>'consent_version');
  return 'saved';
end $$;
revoke all on function public.submit_wuus_inquiry(uuid, text, jsonb) from public, anon, authenticated;
grant execute on function public.submit_wuus_inquiry(uuid, text, jsonb) to service_role;

commit;
